### How to use:
- Query and store their historical data for 2019 in New York 
- How to query:
- API has max 1,000 calls per day and max of 60 calls per minute
- To store:
- Process similar to last project and store in a POSTGRESQL DB
- There are 8765.999 hours in a year
- Therefore will take 16 minutes to make 960 calls in one day
- It will take 9 days of this get the weather data for every hour in 2019
- Ensure I dont go over the limits

- Create Data Dictionary

In [1]:
import json
import pandas as pd

###make this cleaned weather data to give to the model

In [4]:
# Extract the information for the current weather and append to a weather data file
with open("weatherData.json") as json_file:
    w_data = json.load(json_file)

#show this data in a data frame
#number of hours in the data
# around 976 per day?
# Create an empty DataFrame to store the venue data
weather_data = pd.DataFrame(columns=['Latitude', 'Longitude', 'Time Stamp','Temperature (C)', 'Weather ID', 'Weather Main', 'Weather Description', 'Weather Icon', 'Rain 1h', 'Snow 1h'])

#select the first venue
for k in range(len(w_data)):
    data=w_data[k]
    lat=data['lat']
    lon=data['lon']
    time_stamp=data['data'][0]['dt']
    temp=data['data'][0]['feels_like']-273.15#store in celsius
    weather_id=data['data'][0]['weather'][0]['id']
    weather_main=data['data'][0]['weather'][0]['main']
    weather_description=data['data'][0]['weather'][0]['description']
    weather_icon=data['data'][0]['weather'][0]['icon']
    try:
        rain_1h=data['data'][0]['rain']['1h']
    except KeyError:
        rain_1h='NA'
    
    try:
        snow_1h=data['data'][0]['snow']['1h']
    except KeyError:
        snow_1h='NA'

    #append the values information to the DataFrame
    weather_data.loc[k] = [lat,lon,time_stamp,temp,weather_id,weather_main,weather_description,weather_icon,rain_1h,snow_1h]


weather_data.head(20)

,Latitude,Longitude,Time Stamp,Temperature (C),Weather ID,Weather Main,Weather Description,Weather Icon,Rain 1h,Snow 1h
0,40.7834,-73.9663,1546300800,3.86,501,Rain,moderate rain,10n,3.06,NA
1,40.7834,-73.9663,1546304400,2.81,502,Rain,heavy intensity rain,10n,4.31,NA
2,40.7834,-73.9663,1546308000,3.41,502,Rain,heavy intensity rain,10n,4.38,NA
3,40.7834,-73.9663,1546311600,3.60,502,Rain,heavy intensity rain,10n,5.84,NA
4,40.7834,-73.9663,1546315200,5.45,501,Rain,moderate rain,10n,3.77,NA
5,40.7834,-73.9663,1546318800,5.29,502,Rain,heavy intensity rain,10n,3.53,NA
6,40.7834,-73.9663,1546322400,6.00,501,Rain,moderate rain,10n,1.07,NA
7,40.7834,-73.9663,1546326000,6.82,701,Mist,mist,50n,0.47,NA
8,40.7834,-73.9663,1546329600,10.08,701,Mist,mist,50n,NA,NA
9,40.7834,-73.9663,1546333200,10.38,701,Mist,mist,50n,0.25,NA
10,40.7834,-73.9663,1546336800,11.64,701,Mist,mist,50n,0.25,NA
11,40.7834,-73.9663,1546340400,12.60,804,Clouds,overcast clouds,04n,NA,NA
12,40.7834,-73.9663,1546344000,13.22,500,Rain,light rain,10n,0.25,NA
13,40.7834,-73.9663,1546347600,13.40,803,Clouds,broken clouds,04d,NA,NA
14,40.7834,-73.9663,1546351200,13.68,804,Clouds,overcast clouds,04d,NA,NA
15,40.7834,-73.9663,1546354800,13.91,803,Clouds,broken clouds,04d,NA,NA
16,40.7834,-73.9663,1546358400,13.49,500,Rain,light rain,10d,0.5,NA
17,40.7834,-73.9663,1546362000,12.05,800,Clear,clear sky,01d,NA,NA
18,40.7834,-73.9663,1546365600,11.67,500,Rain,light rain,10d,0.5,NA
19,40.7834,-73.9663,1546369200,9.51,803,Clouds,broken clouds,04d,NA,NA

In [5]:
len(weather_data)

8761

In [6]:
#ensure that the difference between timestamps is 3600
j=0
for i in range(1,len(weather_data)):
    if weather_data['Time Stamp'][i]-weather_data['Time Stamp'][i-1]!=3600:
        print('error')
        j+=1

print(j)

0

### Conlsusion:
- Weather data collection going smoothly
- Will do 7 more days worth of calls to get all of 2019

In [1]:
for i in range(1,17):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16